buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 3824115
  services:
    cq: &cq
      name: code_quality
      url: https://dummy-external-service.herokuapp.com/code-analysis
      method: post
      query_params:
        secret: A1234567890Z
      data_from_issue:
        - target-repository
      mapping:
        target_url: target-repository
      headers:
        Authorization: OAUTH-token 123456
        Time-Zone: Europe/Amsterdam
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our community Code of Conduct and Guidelines
          messages:
            - "Our CoC: https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md"
            - "It's adapted from the Contributor Covenant: http://contributor-covenant.org"
            - "Reports of abusive or harassing behavior may be reported to reports@theoj.org"
      - editor_list:
          command: list editors
          description: List all current topic editors
          template_file: editors.md
    list_of_values:
      - reviewers:
          only: editors
          sample_value: "@username"
          add_as_assignee: true
    assign_editor:
      only: editors
    remove_editor:
      only: editors
      no_editor_text: "TBD"
    invite:
      only: editors
    add_remove_assignee:
      only: editors
    check_references:
    repo_checks:
    set_value:
      - version:
          only: editors
          sample_value: "v1.0.0"
      - archive:
          only: editors
          sample_value: "10.21105/joss.12345"
    label_command:
      - review_ok:
          only: editors
          command: review successful
          add_labels:
            - reviewed
            - recommend publication
            - pending publication
          remove_labels:
            - ongoing
            - pending review
      - review_nok:
          only: editors
          command: review failed
          add_labels:
            - recommend rejection
    welcome_template:
      template_file: welcome.md
      data_from_issue:
        - repository
    close_issue_command:
      only: editors
      command: reject
      add_labels:
        - rejected
    external_service:
      - code_quality:
          only: editors
          command: analyze code
          description: Reports on the quality of the code
          message: Inspecting code...
          <<: *cq
      - cat_facts:
          command: tell me something about cats
          description: Random facts about cats
          url: "https://cat-fact.herokuapp.com/facts/random"
          method: get
          query_params:
              animal_type: cat
              amount: 1
          template_file: cats.md
    welcome_external_service:
      <<: *cq
    add_remove_checklist:
      only: editors
      template_file: reviewer_checklist.md
      data_from_issue:
        - target-repository
        - author-handle


