name: Extra Builds

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.failure-allowed }}
    strategy:
      matrix:
        ruby-version: ['head', 'truffleruby', 'jruby']
        failure-allowed: [true]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec ruby -v
        bundle exec rspec spec
